language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-19mode
  - rbx-2.1.1

matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx-2.1.1

  fast_finish: true

services:
  - neo4j

bundler_args: --without production development
